image: python:3.12

stages:
  - quality
  - test
  - publish

variables:
  UV_CACHE_DIR: .uv-cache
  UV_LINK_MODE: copy
  UV_PUBLISH_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi"  
  UV_PUBLISH_USERNAME: "gitlab-ci-token"  
  UV_PUBLISH_PASSWORD: "${CI_JOB_TOKEN}"

.install: &install
  before_script:
    - pip install uv
    - uv sync --group dev
  cache:
    key: uv-$CI_COMMIT_REF_SLUG
    paths:
      - .uv-cache/

.on-mr-and-main:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == "main"

lint:
  extends: .on-mr-and-main
  stage: quality
  tags: [docker]
  <<: *install
  script:
    - uv run pre-commit run --all-files

test:
  extends: .on-mr-and-main
  stage: test
  tags: [docker]
  <<: *install
  script:
    - uv run pytest tests/ -v

publish:
  stage: publish
  tags: [docker]
  before_script:
    - pip install uv
  script:
    - VERSION=$(git describe --exact-match --tags)
    - uvx --from=toml-cli toml set --toml-path=pyproject.toml project.version $VERSION
    - uv build
    - uv publish dist/*
  rules:
    - if: $CI_COMMIT_TAG
